global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Node Exporter (Host Metrics)
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Scrape cAdvisor (Container Metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Scrape Uptime Kuma
  - job_name: 'uptime_kuma'
    static_configs:
      - targets: ['uptime-kuma:3001']

  # Scrape Nginx Exporter
  - job_name: 'nginx_exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']

  # Scrape Grafana and Loki metrics (Internal Monitoring)
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  # Scrape Blackbox Exporter
  - job_name: 'blackbox'
    static_configs:
      - targets: ['blackbox-exporter:9115']

