apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    # Use the internal Docker service name and port
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    version: 1
    editable: true
  - name: Loki
    type: loki
    # Use the internal Docker service name and port
    url: http://loki:3100
    access: proxy
    version: 1
    editable: true

